import { Session } from 'neo4j-driver';
import { Concept } from './concepts';


/** super class to all Graph Generators */
export interface BaseGenerator {

    /** 
     * Generates nodes and relations from previously extracted Concepts and inserts them into the given Neo4j database. 
     * May also use or modify exisitng nodes generated by jQAssistant.
     * */
    run(neo4jSession: Session, concepts: Map<Concept, any>): Promise<void>;
}