import { Session } from 'neo4j-driver';
import { ConceptIndex } from './concept-indexes';
import ConnectionIndex from './connection-index';


/** super class to all Graph Generators */
export default interface BaseGenerator {

    /** 
     * Generates nodes and relations from previously extracted Concepts and inserts them into the given Neo4j database. 
     * May also use or modify exisiting nodes generated by jQAssistant.
     * 
     * Can use `nodeIndexes` to refer to specific, previously LCE-generated nodes.
     * */
    run(neo4jSession: Session, concepts: Map<ConceptIndex, any>, connectionIndex: ConnectionIndex): Promise<void>;
}